-- EXCESS INVENTORY RISK MART
-- Classifies inventory risk using days of supply thresholds

CREATE OR REPLACE TABLE REPORTING.MART_EXCESS_RISK AS
SELECT
    DATE,
    PLANT,
    PRODUCT_ID,
    SUPPLIER,
    INVENTORY_ON_HAND_EOD,
    TOTAL_CONSUMED,
    INVENTORY_VALUE_USD,
    DAYS_OF_SUPPLY,

    CASE
        WHEN DAYS_OF_SUPPLY >= 20 THEN 'HIGH'
        WHEN DAYS_OF_SUPPLY >= 10 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS EXCESS_RISK_LEVEL

FROM MODELED.FACT_INVENTORY_DAILY;

