-- INVENTORY KPI MART
-- High-level KPIs for reporting and dashboards

CREATE OR REPLACE TABLE REPORTING.MART_INVENTORY_KPIS AS
SELECT
    DATE,
    PLANT,

    SUM(INVENTORY_VALUE_USD) AS TOTAL_INVENTORY_VALUE,
    AVG(DAYS_OF_SUPPLY) AS AVG_DAYS_OF_SUPPLY,
    SUM(TOTAL_CONSUMED) AS TOTAL_CONSUMED,
    SUM(TOTAL_PURCHASED) AS TOTAL_PURCHASED

FROM MODELED.FACT_INVENTORY_DAILY
GROUP BY DATE, PLANT;

