-- RAW INVENTORY OPERATIONS TABLE
-- This table stores daily operational inventory data before transformations

CREATE OR REPLACE TABLE RAW.RAW_INVENTORY_OPS (
    DATE DATE,
    PLANT STRING,
    PRODUCT_ID STRING,
    SUPPLIER STRING,
    UNITS_PURCHASED NUMBER,
    UNITS_CONSUMED NUMBER,
    INVENTORY_ON_HAND_EOD NUMBER,
    UNIT_COST_USD NUMBER(10,2),
    LEAD_TIME_DAYS NUMBER,
    FORECAST_UNITS NUMBER
);

