-- FACT INVENTORY DAILY
-- Aggregated daily inventory metrics by plant, product, supplier

CREATE OR REPLACE TABLE MODELED.FACT_INVENTORY_DAILY AS
SELECT
    DATE,
    PLANT,
    PRODUCT_ID,
    SUPPLIER,

    SUM(UNITS_PURCHASED) AS TOTAL_PURCHASED,
    SUM(UNITS_CONSUMED) AS TOTAL_CONSUMED,
    AVG(INVENTORY_ON_HAND_EOD) AS INVENTORY_ON_HAND_EOD,

    ROUND(AVG(INVENTORY_ON_HAND_EOD) * AVG(UNIT_COST_USD), 2)
        AS INVENTORY_VALUE_USD,

    ROUND(
        AVG(INVENTORY_ON_HAND_EOD) / NULLIF(AVG(UNITS_CONSUMED), 0),
        2
    ) AS DAYS_OF_SUPPLY

FROM RAW.RAW_INVENTORY_OPS
GROUP BY
    DATE, PLANT, PRODUCT_ID, SUPPLIER;

